### ISSUE TITLE
Add ability to add new creator entries directly from issue entry page.

### ISSUE THREAD

**Issue by THElegend5** [bpepple/metron#175] opened 2023-08-29 12:57 UTC
**Is your feature request related to a problem? Please describe.**
Currently you have to switch a ton of tabs just to add a new issue as a result of new staff entries currently not in metron.

**Describe the solution you'd like**
Having the ability to add staff directly from the issue addition page would be nice. This can be in the form of a button which shows up if there are no matching names for the staff like is the case for comicvine.

**Additional context**
![image](https://github.com/bpepple/metron/assets/63903377/69049f0f-be58-4d74-aaad-f1b1ebc6f4d7)

**Comment by bpepple** [comment] 2024-01-24 17:55
This sounds like the current behavior of the issue entry page, which allows you to add a new creator from the widget is one doesn't already exist. Going to close this as **Not a Bug**, but if that isn't behavior you were expecting please add more information to describe when reopening.

**Comment by THElegend5** [comment] 2024-01-25 14:33
> This sounds like the current behavior of the issue entry page, which allows you to add a new creator from the widget is one doesn't already exist. Going to close this as **Invalid**, but if that isn't behavior you were expecting please add more information to describe when reopening.

That still doesn't seem to be the case as far as I can tell
![image](https://github.com/bpepple/metron/assets/63903377/51008740-9b45-4578-9f65-4d64d0ef6d60)
It still only shows creator not found but there is no add this item as is the case on comicvine if the creator is not found.
So you don't have to leave the page to add the creator and come back and add it directly from issue entry if the creator doesn't already exist on metron. And can add the details of the creator later once you have added the issue by going to that particular creators entry.

**Closed** 2024-01-30 21:08 UTC
Labels: bug
